from zeep import Client

# client = Client('file:////E:\ivan_code\linux_atserver\SpRc.wsdl')
client = Client('E:\ivan_code\linux_atserver\SpRc.wsdl')
print(client)
res = client.service.OpenSession()
# res1 = client.service.GetPlayoutInfo()
res1 = client.service.GetPlayoutStatus()
# res2 = client.service.CloseSession()

# res1 = client.service.ScanPorts()
# print(res)
# print(res1)
# print(res2)
print(dir(res1))
print(res1.PlayoutStatus)
print(type(res1.PlayoutStatus))
# print(dir(res1.PlayoutInfo))
# print(res1.PlayoutStatus.SymRate)
# print(res1.SpRcResult)
